# Generated by Django 4.0.10 on 2024-11-25 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0002_alter_faculty_students'),
        ('subjects', '0002_subject_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='faculties.faculty'),
        ),
    ]
