# Generated by Django 4.0.10 on 2024-11-25 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0004_alter_faculty_subject'),
        ('subjects', '0004_remove_subject_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='faculties.faculty'),
        ),
    ]
