# Generated by Django 4.0.10 on 2024-11-25 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_subjects'),
        ('subjects', '0004_remove_subject_faculty'),
        ('faculties', '0002_alter_faculty_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='faculties', to='students.student'),
        ),
    ]
